DROP TABLE `demo_table`
CREATE TABLE IF NOT EXISTS `demo_table`
(
    `id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `name` VARCHAR (100) DEFAULT NULL,
    `exist` BOOLEAN NOT NULL DEFAULT FALSE
)
